---
title: "p8105_hw5_wz2506"
author: "Weiran Zhang"
date: "11/9/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, include = FALSE}

library(readxl)
library(rvest)
library(broom)

```

**Problem 1**

```{r}
library(tidyverse)

set.seed(10)

iris_with_missing = iris %>% 
  map_df(~replace(.x, sample(1:150, 20), NA)) %>%
  mutate(Species = as.character(Species))

iris_with_missing

```

```{r}
##Function replacing missing values
replace_missing = function(x) {
  if (is.numeric(x)) {
    replace(x, is.na(x), mean(x, na.rm = TRUE))
  } else if(is.character(x)){
    replace(x, is.na(x), "virginica")
  }
}

```

```{r}

output = vector("list", length = 5) ##define an output list
for (i in 1:5) {
  output[[i]] = replace_missing(iris_with_missing[[i]])
  } ##for-loop apply the function
output = map(iris_with_missing, replace_missing)
as_tibble(output) ##make the output an an tidied table form

```

**Problem 2**

```{r}

files = as.data.frame(list.files(path = "./data/", pattern = "*.csv"))
colnames(files) = "file_names"

files

```

```{r}

read_file = function(file_names){
  read_csv(paste0("./data/", file_names))
}

output = purrr::map(files$file_names, read_file)

file_nest = 
  files %>%
  mutate(data = output) %>%
  unnest()

file_nest ##dataframe with file names and data in each files

```

```{r}

file_tidy = file_nest %>%
  pivot_longer(week_1:week_8,
               names_to = "week",
               values_to = "data") %>%
  mutate(files = str_remove(file_names, ".csv"),
         week = str_remove(week, "week_")) %>%
  separate(file_names, into = c("group", "subject_id"), sep = "_") %>%
  mutate(group = recode(group, "con" = "control", "exp" = "experimental")) 

file_tidy
  

```